# Site settings
title: 'Brijesh Bhakta'
email: brijeshbhakta30@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular and React
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brijeshbhakta.com" # the base hostname & protocol for your site
twitter_username: brijesh_bhakta
github_username:  brijeshbhakta30
include: [_pages]
exclude: ['node_modules']
paginate: 11
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown
highlighter: rouge

# Gems
gems: [jekyll-paginate]
