packages:
  - "."
  - "workers/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - eslint-config-blazex

saveExact: true
storeDir: .pnpm-store
